### ISSUE TITLE
Question on reproducing AlignScore results

### ISSUE THREAD

**Issue by cs329yangzhong** [amazon-science/tofueval#3]
I need some help replicating the results in the paper. I wonder if you plan to release aggregated files for summary-level labels so I can do a cross-check. 

## Summary-Level
Below is my result on summary-level Balanced Accuracy using AlignScore (their released large checkpoint).

I tuned the threshold on the dev set `(df_val_temp = df_val[(df_val.dataset == origin) & (df_val.topic_split == topic)]`

<img width="443" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/3105515d-1ab1-4773-b53c-e9ac8cdfa23d">

The original paper has
<img width="213" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/f73157fe-003d-422f-bbb4-38434d72478c">

Since I derive the summary-level labels from your raw files, I wonder if the authors can help check the converted label distribution.
<img width="672" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/eb926164-d353-48e2-8598-94d69b216f04">

<img width="675" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/1c82a4e7-9561-48b9-9975-63a243c2fcb2">

## Sentence-Level
There are several typos in the provided files under the folder `factual_consistency` See Issue #4 , After fixing them (I changed the sent_idx for the first two typos and removed the duplicated row with the "yes" label for the last), my scores are lower than the paper reported. Could the authors help verify whether the results in the paper can be easily reproduced?

<img width="439" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/7fb82d9e-8ba7-476b-9fe2-39466619c63d">

The paper has
<img width="310" alt="image" src="https://github.com/amazon-science/tofueval/assets/31517298/06179a60-52d8-4a8b-ac56-85fc0b34b87c">

Thanks!

**Comment by Liyan06** [comment]
Hi, the results in the paper is based on the annotations on the initial five models. Are you including the rows for the added model annotations?

**Comment by cs329yangzhong** [comment]
Yes, I excluded model_extra, and the test size is 444, matching with the paper.
![image](https://github.com/amazon-science/tofueval/assets/31517298/d5ebef47-55de-4ec2-bd27-e60bd5afeee6)

**Comment by Liyan06** [comment]
Thanks for letting me know. I'll get back to you on this over the weekend!

**Comment by Liyan06** [comment]
Hi, the distribution on both sentence and summary-level looks good to me! I have the same result as yours!

For the balanced accuracy results, It's usually hard to replicate the exact same numbers but I think your numbers is close enough with those in the paper. The only big difference is AlignScore on summary-level medium main topics, which probably due to the accumulation of errors on sentence-level. If you have a systematic way to compare all models using the same code skeleton for eval in your future work, this should be less a concern (the relevant performance/ranking of models would not change).

**Comment by cs329yangzhong** [comment]
Thank you for confirming the distributions. Regarding the big discrepancy in summary-level mediaSum, for the sum main topic evaluation, could you share the aggregated summary-level labels for verification?

**Comment by Liyan06** [comment]
Sure! Can you show me your processed summary-level labels?

**Comment by cs329yangzhong** [comment]
I combined all datasets [here](https://drive.google.com/file/d/1Yv85UU1mozEy0xVt8BeTHx_amj2it8Y9/view?usp=sharing)

**Comment by Liyan06** [comment]
Oh, I see. I saw your label distribution above. That was what I asked for.

Here is the stats, which is the same as yours.

MediaSum:
Main: Yes: 89; No: 59
Marginal: Yes: 37; No: 37

mediasum:
Main: Yes: 114; No: 44
Marginal: Yes: 24; No: 40

**Comment by cs329yangzhong** [comment]
Thanks! Then the issue might be related to the AlignScore inferences (I used [AlignScore Large checkpoint](https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-large.ckpt)  and the way we constructed the full summary (I concatenate the summary-sentences with "\n").
